In [18]:
import pandas as pd

In [19]:
pip install kagglehub

Requirement already satisfied: kagglehub in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.3.4)
Requirement already satisfied: packaging in /Users/luckyc/Library/Python/3.13/lib/python/site-packages (from kagglehub) (24.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->kagglehub) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("CooperUnion/anime-recommendations-database")

print("Path to dataset files:", path)

Path to dataset files: /Users/luckyc/.cache/kagglehub/datasets/CooperUnion/anime-recommendations-database/versions/1

In [21]:
import numpy as np

In [22]:
#get the anime dataset

anime_data = pd.read_csv("anime.csv")

In [23]:
#get rating dataset
anime_rating = pd.read_csv("rating.csv")

In [32]:
#number of rows and columns in anime dataset
data_shape = anime_data.shape
print(f" The DataFrame has {data_shape[0]} rows and {data_shape[1]} columns! \n")
print(anime_data.info())

 The DataFrame has 12294 rows and 7 columns!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB
None

In [25]:
#number of rows and colums in rating dataset
rating_shape = anime_rating.shape
print(f" The DataFrame has {rating_shape[0]} rows and {rating_shape[1]} columns! \n")
print(anime_rating.info())

 The DataFrame has 7813737 rows and 3 columns!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB
None

In [33]:
#top 5 rows 
anime_data.head(5)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [27]:
#last 5 rows
anime_data.tail(5)

,anime_id,name,genre,type,episodes,rating,members
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [28]:
#top 5 rows of rating
anime_rating.head(5)

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [29]:
#last 5 rows of rating
anime_rating.tail(5)

         user_id  anime_id  rating
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

In [30]:
#checking for null, empty for data
null_anime = anime_data.isnull()
print(null_anime)

       anime_id   name  genre   type  episodes  rating  members
0         False  False  False  False     False   False    False
1         False  False  False  False     False   False    False
2         False  False  False  False     False   False    False
3         False  False  False  False     False   False    False
4         False  False  False  False     False   False    False
...         ...    ...    ...    ...       ...     ...      ...
12289     False  False  False  False     False   False    False
12290     False  False  False  False     False   False    False
12291     False  False  False  False     False   False    False
12292     False  False  False  False     False   False    False
12293     False  False  False  False     False   False    False

[12294 rows x 7 columns]

In [31]:
#checking for null, empty for rating
null_rating = anime_rating.isnull()
print(null_rating)

         user_id  anime_id  rating
0          False     False   False
1          False     False   False
2          False     False   False
3          False     False   False
4          False     False   False
...          ...       ...     ...
7813732    False     False   False
7813733    False     False   False
7813734    False     False   False
7813735    False     False   False
7813736    False     False   False

[7813737 rows x 3 columns]

In [34]:
# checking if any values are null in data of anime data
print(anime_data.isnull().any().any())

True

In [36]:
# Getting a count of null values in each column
anime_data.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [37]:
#Column names for anime data
anime_data.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [40]:
#using describe for anime data
pd.options.display.float_format = "{:,.2f}".format
anime_data.describe()

       anime_id    rating      members
count 12,294.00 12,064.00    12,294.00
mean  14,058.22      6.47    18,071.34
std   11,455.29      1.03    54,820.68
min        1.00      1.67         5.00
25%    3,484.25      5.88       225.00
50%   10,260.50      6.57     1,550.00
75%   24,794.50      7.18     9,437.00
max   34,527.00     10.00 1,013,917.00

In [35]:
# checking if any values are null in data of anime rating
print(anime_rating.isnull().any().any())

False

In [38]:
#column names for anime rating
anime_rating.columns

Index(['user_id', 'anime_id', 'rating'], dtype='object')

In [41]:
#using describe for anime rating
pd.options.display.float_format = "{:,.2f}".format
anime_rating.describe()

           user_id     anime_id       rating
count 7,813,737.00 7,813,737.00 7,813,737.00
mean     36,727.96     8,909.07         6.14
std      20,997.95     8,883.95         3.73
min           1.00         1.00        -1.00
25%      18,974.00     1,240.00         6.00
50%      36,791.00     6,213.00         7.00
75%      54,757.00    14,093.00         9.00
max      73,516.00    34,519.00        10.00

In [43]:
#time to clean starting with anime data
def clean_anime(anime_data) -> pd.DataFrame:
    anime_data.columns = anime_data.columns.str.title()
    anime_data.columns = anime_data.columns.str.strip().str.replace('_', ' ')

    # Drop unnecessary columns
    cols_to_drop = ['episodes']
    anime_data = anime_data.drop(columns=cols_to_drop)

    # Drop rows with missing values
    anime_data = anime_data.dropna()

    return anime_data

In [45]:
#time to clean starting with anime rating
def clean_anime_rating(anime_rating) -> pd.DataFrame:
    anime_rating.columns = anime_rating.columns.str.title()
    anime_rating.columns= anime_rating.columns.str.strip().str.replace('_', ' ')

    # Drop unnecessary columns - not needed in this case
    

    # Drop rows with missing values
    anime_rating = anime_rating.dropna()

    return anime_rating

In [46]:
# Call function clean

anime_data_clean = clean_anime(anime_data)
anime_data_clean.head(5)

,Anime Id,Name,Genre,Type,Episodes,Rating,Members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [47]:
anime_rating_clean = clean_anime_rating(anime_rating)
anime_rating_clean.head(5)

   User Id  Anime Id  Rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1